# Generated by Django 3.2.6 on 2021-10-22 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_troop_troop_cookie_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troop',
            name='troop_cookie_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
