# Generated by Django 3.2.8 on 2021-11-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_booth_tickets_per_week_troop_total_booth_tickets_per_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='troop',
            options={'permissions': (('troop_creation', 'Create a troop'), ('troop_updates', 'Updates a troop'), ('troop_deletion', 'Deletes a troop')), 'verbose_name': 'troop', 'verbose_name_plural': 'troops'},
        ),
        migrations.AddField(
            model_name='troop',
            name='troop_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
