# Generated by Django 3.2.8 on 2021-11-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211129_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troop',
            name='troop_cookie_coordinator',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
