# Generated by Django 3.2.6 on 2021-12-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_troop_troop_cookie_coordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troop',
            name='daisy_troop',
        ),
        migrations.AddField(
            model_name='troop',
            name='troop_level',
            field=models.SmallIntegerField(choices=[(1, 'Daisies'), (2, 'Brownies'), (3, 'Juniors'), (4, 'Cadettes'), (5, 'Seniors'), (6, 'Ambassadors')], default=0),
        ),
    ]
