# Generated by Django 3.2.6 on 2021-12-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211213_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troop',
            name='troop_number',
            field=models.IntegerField(unique=True),
        ),
    ]
