# Generated by Django 3.2.6 on 2022-03-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("troops", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="troop",
            name="super_troop",
        ),
        migrations.AddField(
            model_name="troop",
            name="troop_size",
            field=models.SmallIntegerField(default=0),
        ),
    ]
