# Generated by Django 3.2.6 on 2022-12-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troops', '0002_auto_20220308_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troop',
            name='troop_cookie_coordinator',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
