# Generated by Django 3.2.6 on 2022-12-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troops', '0003_alter_troop_troop_cookie_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_troop_total_tickets_per_week', models.IntegerField(default=5)),
                ('small_troop_golden_tickets_per_week', models.IntegerField(default=1)),
                ('medium_troop_additional_golden_tickets', models.IntegerField(default=1)),
                ('large_troop_additional_golden_tickets', models.IntegerField(default=2)),
            ],
        ),
    ]
