# Generated by Django 3.2.6 on 2022-12-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troops', '0004_ticketparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroopSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_troop_size', models.IntegerField(default=8)),
                ('large_troop_size', models.IntegerField(default=10)),
            ],
        ),
    ]
