# Generated by Django 3.2.8 on 2021-10-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_booths', '0002_auto_20211016_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_location', models.CharField(max_length=300)),
                ('booth_address', models.CharField(max_length=300)),
                ('booth_enabled', models.BooleanField(default=False)),
                ('booth_is_golden_ticket', models.BooleanField(default=False)),
                ('booth_requires_masks', models.BooleanField(default=False)),
                ('booth_is_outside', models.BooleanField(default=False)),
                ('booth_notes', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'booth location',
                'verbose_name_plural': 'booth locations',
            },
        ),
        migrations.RemoveField(
            model_name='booth_block',
            name='booth_block_is_golden_ticket',
        ),
        migrations.AddField(
            model_name='booth_block',
            name='booth_block_current_troop_owner',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booth_block',
            name='booth_block_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booth_block',
            name='booth_block_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booth_day',
            name='booth_day_close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booth_day',
            name='booth_day_hours_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booth_day',
            name='booth_day_open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booth_block',
            name='booth_block_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booth_block',
            name='booth_block_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booth_block',
            name='booth_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookie_booths.booth_day'),
        ),
        migrations.AlterField(
            model_name='booth_day',
            name='booth_day_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booth_day',
            name='booth_day_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booth_day',
            name='booth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookie_booths.booth_location'),
        ),
        migrations.DeleteModel(
            name='Booths',
        ),
    ]
