# Generated by Django 3.2.8 on 2021-11-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_booths', '0003_auto_20211024_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_block_start_time', models.TimeField(blank=True, null=True)),
                ('booth_block_end_time', models.TimeField(blank=True, null=True)),
                ('booth_block_current_troop_owner', models.SmallIntegerField(default=0)),
                ('booth_block_reserved', models.BooleanField(default=False)),
                ('booth_block_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BoothDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_day_date', models.DateField(blank=True, null=True)),
                ('booth_day_hours_set', models.BooleanField(default=False)),
                ('booth_day_open_time', models.TimeField(blank=True, null=True)),
                ('booth_day_close_time', models.TimeField(blank=True, null=True)),
                ('booth_day_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BoothHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_start_date', models.DateField(blank=True, null=True)),
                ('booth_end_date', models.DateField(blank=True, null=True)),
                ('sunday_open', models.BooleanField(default=False)),
                ('sunday_open_time', models.TimeField(blank=True, null=True)),
                ('sunday_close_time', models.TimeField(blank=True, null=True)),
                ('monday_open', models.BooleanField(default=False)),
                ('monday_open_time', models.TimeField(blank=True, null=True)),
                ('monday_close_time', models.TimeField(blank=True, null=True)),
                ('tuesday_open', models.BooleanField(default=False)),
                ('tuesday_open_time', models.TimeField(blank=True, null=True)),
                ('tuesday_close_time', models.TimeField(blank=True, null=True)),
                ('wednesday_open', models.BooleanField(default=False)),
                ('wednesday_open_time', models.TimeField(blank=True, null=True)),
                ('wednesday_close_time', models.TimeField(blank=True, null=True)),
                ('thursday_open', models.BooleanField(default=False)),
                ('thursday_open_time', models.TimeField(blank=True, null=True)),
                ('thursday_close_time', models.TimeField(blank=True, null=True)),
                ('friday_open', models.BooleanField(default=False)),
                ('friday_open_time', models.TimeField(blank=True, null=True)),
                ('friday_close_time', models.TimeField(blank=True, null=True)),
                ('saturday_open', models.BooleanField(default=False)),
                ('saturday_open_time', models.TimeField(blank=True, null=True)),
                ('saturday_close_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoothLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_location', models.CharField(max_length=300)),
                ('booth_address', models.CharField(max_length=300)),
                ('booth_enabled', models.BooleanField(default=False)),
                ('booth_is_golden_ticket', models.BooleanField(default=False)),
                ('booth_requires_masks', models.BooleanField(default=False)),
                ('booth_is_outside', models.BooleanField(default=False)),
                ('booth_notes', models.CharField(max_length=100)),
                ('booth_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookie_booths.boothhours')),
            ],
            options={
                'verbose_name': 'booth location',
                'verbose_name_plural': 'booth locations',
            },
        ),
        migrations.RemoveField(
            model_name='booth_day',
            name='booth',
        ),
        migrations.DeleteModel(
            name='Booth_Block',
        ),
        migrations.DeleteModel(
            name='Booth_Day',
        ),
        migrations.DeleteModel(
            name='Booth_Location',
        ),
        migrations.AddField(
            model_name='boothday',
            name='booth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookie_booths.boothlocation'),
        ),
        migrations.AddField(
            model_name='boothblock',
            name='booth_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookie_booths.boothday'),
        ),
    ]
