# Generated by Django 3.2.6 on 2022-10-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookie_booths", "0003_auto_20221008_2047"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boothblock",
            options={
                "permissions": (
                    ("block_reservation", "Reserve/Cancel a booth"),
                    ("reserve_block", "Reserve a booth"),
                    (
                        "cookie_captain_reserve_block",
                        "Reserve a block for a daisy scout",
                    ),
                    (
                        "block_reservation_admin",
                        "Administrator reserve/cancel any booth",
                    ),
                    (
                        "admin_hold_block_for_cookie_captains",
                        "Administrator hold blocks for cookie captains to reserve",
                    ),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="boothday",
            options={
                "permissions": (
                    ("toggle_day", "Enable/Disable a day for a booth"),
                    ("add_or_update_hours", "Add or update hours for a booth day"),
                    ("make_golden_booth", "Make a booth day golden"),
                    ("toggle_freeforall", "Enable/Disable free for all"),
                )
            },
        ),
        migrations.AddField(
            model_name="boothblock",
            name="booth_block_held_for_cookie_captains",
            field=models.BooleanField(default=False),
        ),
    ]
