# Generated by Django 3.2.6 on 2022-10-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_booths', '0005_alter_boothblock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='boothblock',
            name='booth_block_daisy_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boothblock',
            name='booth_block_daisy_troop_owner',
            field=models.IntegerField(default=0),
        ),
    ]
