# Generated by Django 3.2.6 on 2022-12-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_booths', '0006_auto_20221031_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_start_date', models.DateField(blank=True, null=True)),
                ('season_end_date', models.DateField(blank=True, null=True)),
                ('real_season_start_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
