# Generated by Django 3.2.8 on 2021-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_booths', '0006_alter_boothlocation_booth_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boothblock',
            name='booth_block_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boothblock',
            name='booth_block_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boothday',
            name='booth_day_close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boothday',
            name='booth_day_open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
