# Generated by Django 3.2.6 on 2022-12-19 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_booths', '0007_cookieseason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boothhours',
            options={'verbose_name_plural': 'Booth hours'},
        ),
    ]
