# Generated by Django 3.2.8 on 2021-11-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_booths', '0009_auto_20211121_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boothhours',
            name='booth_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookie_booths.boothlocation'),
        ),
    ]
