# Generated by Django 3.2.6 on 2022-12-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_booths', '0009_auto_20221222_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookieseason',
            name='ffa_day_of_week',
            field=models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=1),
        ),
    ]
