# Generated by Django 5.0.7 on 2024-08-24 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("cookie_booths", "0012_remove_boothhours_friday_close_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boothblock",
            options={
                "permissions": (
                    ("block_reservation", "Reserve/Cancel a booth"),
                    ("reserve_block", "Reserve a booth"),
                    (
                        "cookie_captain_reserve_block",
                        "Reserve a block for a daisy scout",
                    ),
                    (
                        "block_reservation_admin",
                        "Administrator reserve/cancel any booth, or hold booths for reservation",
                    ),
                )
            },
        ),
        migrations.RemoveField(
            model_name="boothblock",
            name="booth_block_current_cookie_captain_owner",
        ),
        migrations.RemoveField(
            model_name="boothblock",
            name="booth_block_current_troop_owner",
        ),
        migrations.AddField(
            model_name="boothblock",
            name="owner_content_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="boothblock",
            name="owner_object_id",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
