# Generated by Django 5.0.7 on 2024-09-04 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookie_booths", "0013_alter_boothblock_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boothblock",
            options={
                "permissions": (
                    ("reserve_block_tcc", "Reserve a booth"),
                    ("reserve_block_captain", "Reserve a block for a daisy troop"),
                    (
                        "reserve_block_admin",
                        "Reserve/cancel any booth or hold booths for captains",
                    ),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="boothday",
            options={"permissions": (("update_booth_day", "Update booth day"),)},
        ),
        migrations.RemoveField(
            model_name="boothblock",
            name="owner_content_type",
        ),
        migrations.RemoveField(
            model_name="boothblock",
            name="owner_object_id",
        ),
        migrations.AddField(
            model_name="boothblock",
            name="booth_block_current_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
