# Generated by Django 5.0.7 on 2024-09-09 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cookie_booths",
            "0014_alter_boothblock_options_alter_boothday_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="boothday",
            old_name="booth",
            new_name="booth_location",
        ),
        migrations.AddField(
            model_name="boothlocation",
            name="booth_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boothlocation",
            name="booth_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BoothDailyAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_attributes", models.JSONField(default=dict)),
                (
                    "booth_location",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cookie_booths.boothlocation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Booth Daily Attributes",
            },
        ),
        migrations.DeleteModel(
            name="BoothHours",
        ),
    ]
