# Generated by Django 5.0.7 on 2024-09-28 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookie_booths", "0015_rename_booth_boothday_booth_location_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BoothDailyAttributes",
            new_name="BoothSchedule",
        ),
        migrations.RenameField(
            model_name="boothschedule",
            old_name="daily_attributes",
            new_name="booth_schedule",
        ),
        migrations.AddField(
            model_name="cookieseason",
            name="daisy_starting_weeks_offset",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="boothlocation",
            name="booth_end_date",
            field=models.DateField(blank=True, default="2023-01-01", null=True),
        ),
        migrations.AlterField(
            model_name="boothlocation",
            name="booth_start_date",
            field=models.DateField(blank=True, default="2023-01-01", null=True),
        ),
        migrations.AlterField(
            model_name="cookieseason",
            name="ffa_day_of_week",
            field=models.SmallIntegerField(
                choices=[
                    (0, "MONDAY"),
                    (1, "TUESDAY"),
                    (2, "WEDNESDAY"),
                    (3, "THURSDAY"),
                    (4, "FRIDAY"),
                    (5, "SATURDAY"),
                    (6, "SUNDAY"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="BoothTimeBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booth_block_start_time", models.DateTimeField(blank=True, null=True)),
                ("booth_block_end_time", models.DateTimeField(blank=True, null=True)),
                ("booth_block_enabled", models.BooleanField(default=False)),
                ("booth_block_freeforall_enabled", models.BooleanField(default=False)),
                (
                    "booth_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cookie_booths.boothday",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("reserve_block_tcc", "Reserve a booth"),
                    ("reserve_block_captain", "Reserve a block for a daisy troop"),
                    (
                        "reserve_block_admin",
                        "Reserve/cancel any booth or hold booths for captains",
                    ),
                ),
            },
        ),
        migrations.DeleteModel(
            name="BoothBlock",
        ),
    ]
