# Generated by Django 5.0.7 on 2024-09-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookie_booths", "0016_rename_boothdailyattributes_boothschedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boothlocation",
            name="booth_end_date",
            field=models.DateField(default="2023-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="boothlocation",
            name="booth_start_date",
            field=models.DateField(default="2023-01-01"),
            preserve_default=False,
        ),
    ]
