# Generated by Django 5.0.7 on 2024-10-12 18:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookie_booths", "0017_alter_boothlocation_booth_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boothschedule",
            options={"verbose_name_plural": "Booth Schedules"},
        ),
        migrations.RemoveField(
            model_name="boothday",
            name="booth_day_hours_set",
        ),
        migrations.RemoveField(
            model_name="boothlocation",
            name="booth_end_date",
        ),
        migrations.RemoveField(
            model_name="boothlocation",
            name="booth_start_date",
        ),
        migrations.AddField(
            model_name="boothschedule",
            name="booth_end_date",
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="boothschedule",
            name="booth_start_date",
            field=models.DateField(default=datetime.date(2024, 1, 31)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="boothlocation",
            name="booth_block_level_restrictions_end",
            field=models.SmallIntegerField(
                choices=[
                    (0, "NONE"),
                    (1, "DAISIES"),
                    (2, "BROWNIES"),
                    (3, "JUNIORS"),
                    (4, "CADETTES"),
                    (5, "SENIORS"),
                    (6, "AMBASSADORS"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="boothlocation",
            name="booth_block_level_restrictions_start",
            field=models.SmallIntegerField(
                choices=[
                    (0, "NONE"),
                    (1, "DAISIES"),
                    (2, "BROWNIES"),
                    (3, "JUNIORS"),
                    (4, "CADETTES"),
                    (5, "SENIORS"),
                    (6, "AMBASSADORS"),
                ],
                default=0,
            ),
        ),
    ]
