# Generated by Django 5.0.7 on 2024-10-12 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookie_booths", "0018_alter_boothschedule_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boothschedule",
            name="booth_end_date",
            field=models.DateField(default=datetime.date(2024, 2, 25)),
        ),
        migrations.AlterField(
            model_name="boothschedule",
            name="booth_start_date",
            field=models.DateField(default=datetime.date(2024, 1, 14)),
        ),
    ]
