# Generated by Django 5.0.7 on 2024-10-12 18:54

import cookie_booths.models.schedule
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookie_booths", "0019_alter_boothschedule_booth_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boothschedule",
            name="booth_end_date",
            field=models.DateField(
                default=cookie_booths.models.schedule.get_default_end_date
            ),
        ),
        migrations.AlterField(
            model_name="boothschedule",
            name="booth_start_date",
            field=models.DateField(
                default=cookie_booths.models.schedule.get_default_start_date
            ),
        ),
    ]
