# Generated by Django 3.2.6 on 2022-12-11 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_user_userpreferences_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
