# Generated by Django 3.2.6 on 2022-12-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userpreferences_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name_plural': 'User Preferences'},
        ),
    ]
