# Generated by Django 3.2.6 on 2022-12-13 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userpreferences_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='id',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
