# Generated by Django 5.0.7 on 2024-09-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auto_20221213_0252"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("cookie_captain", "Cookie Captain"),
                    ("cookie_admin", "Cookie Admin"),
                    ("cookie_staff", "Cookie Staff"),
                    ("tcc", "TCC"),
                    ("unassigned", "Unassigned"),
                ],
                default="unassigned",
                max_length=20,
            ),
        ),
    ]
