# Generated by Django 3.2.6 on 2021-10-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_troop_troop_cookie_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troop',
            name='troop_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
