# Generated by Django 3.2.8 on 2021-11-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_troop_troop_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='troop',
            name='booth_golden_tickets_per_week',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='troop',
            name='booth_tickets_per_week',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
