# Generated by Django 3.2.8 on 2021-11-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211120_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='troop',
            old_name='booth_tickets_per_week',
            new_name='total_booth_tickets_per_week',
        ),
    ]
