# Generated by Django 3.2.6 on 2021-10-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_location', models.CharField(max_length=300)),
                ('booth_requires_masks', models.BooleanField()),
                ('booth_is_outside', models.BooleanField()),
                ('booth_free_text', models.CharField(max_length=100)),
                ('booth_enabled', models.BooleanField()),
            ],
        ),
    ]
