# Generated by Django 3.2.8 on 2021-11-21 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_booths', '0008_auto_20211120_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boothlocation',
            name='booth_hours',
        ),
        migrations.AddField(
            model_name='boothhours',
            name='booth_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cookie_booths.boothlocation'),
        ),
        migrations.AlterField(
            model_name='boothlocation',
            name='booth_notes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
