# Generated by Django 3.2.8 on 2021-11-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_booths', '0010_alter_boothhours_booth_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boothblock',
            options={'permissions': (('cancel_block', 'Cancel a booth'), ('reserve_block', 'Reserve a booth'))},
        ),
        migrations.AlterModelOptions(
            name='boothday',
            options={'permissions': (('enable_day', 'Enable a day for a booth'), ('disable_day', 'Disable a day for a booth'), ('add_or_update_hours', 'Add or update hours for a booth day'), ('enable_freeforall', 'Enable free for all'), ('disable_freeforall', 'Disable free for all'))},
        ),
        migrations.AlterModelOptions(
            name='boothlocation',
            options={'permissions': (('booth_loc_creation', 'Creates a booth location'), ('booth_loc_updates', 'Updates a booth location'), ('booth_loc_deletes', 'Deletes a booth location')), 'verbose_name': 'booth location', 'verbose_name_plural': 'booth locations'},
        ),
    ]
