# Generated by Django 3.2.8 on 2021-12-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_booths', '0011_auto_20211129_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boothblock',
            options={'permissions': (('cancel_block', 'Cancel a booth'), ('reserve_block', 'Reserve a booth'), ('cancel_block_admin', 'Administrator cancel any booth'), ('reserve_block_admin', 'Administrator reserve any booth'))},
        ),
        migrations.AlterModelOptions(
            name='boothday',
            options={'permissions': (('enable_day', 'Enable a day for a booth'), ('disable_day', 'Disable a day for a booth'), ('add_or_update_hours', 'Add or update hours for a booth day'), ('make_golden_booth', 'Make a booth day golden'), ('enable_freeforall', 'Enable free for all'), ('disable_freeforall', 'Disable free for all'))},
        ),
        migrations.RemoveField(
            model_name='boothlocation',
            name='booth_is_golden_ticket',
        ),
        migrations.AddField(
            model_name='boothday',
            name='booth_day_is_golden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boothhours',
            name='friday_golden_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boothhours',
            name='monday_golden_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boothhours',
            name='saturday_golden_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boothhours',
            name='sunday_golden_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boothhours',
            name='thursday_golden_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boothhours',
            name='tuesday_golden_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boothhours',
            name='wednesday_golden_ticket',
            field=models.BooleanField(default=False),
        ),
    ]
